baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
pagination.pagerSize = "9"

[permalinks]
	page = "/:contentbasename/"
	about = "/:contentbasename/"
	episode = "/:contentbasename/"